# -*- coding:utf-8 -*-
# 文件名称：Lyy-去重测试
# 作者:清许丶
# 谨记:遵守秩序，尊重选择。
# 创建时间：2020/11/2 16:41


unnormal_member_org_list = ['muyingyuan', 'mamibaobei', 'sunnybaby', 'harneybaby', 'lebao', 'yqmamalove', 'bzyqyy', 'xwmaidibaby', 'czhjyy', 'lxdodoisland', 'gdxtzgg', 'sysjza', 'qyhappybaby', 'scayf', 'aqjbb', 'hfyybs', 'yfxty', 'yymml', 'ptbbboom', 'ddjsts', 'hshjmy', 'kpdcyy', 'hmmy', 'ya0697', 'ya0782', 'ya0783', 'ya0799', 'ya0800', 'ya0809', 'ya0810', 'ya0897', 'ya0898', 'ya0899']
unnormal_prize_org_list = ['jinyaolan', 'aitiantian', 'muyingyuan', 'ygyj', 'loveheart', 'jinbaby', 'leyaya', 'aiying', 'jiajia', 'yyplan', 'yingyuan', 'beibei', 'mamibaobei', 'yybb', 'jdb', 'dd', 'mamabb', 'sunnybaby', 'muyingfang', 'wlmami', 'dtaiyingfang', 'loveangel', 'harneybaby', 'lebao', 'subujyl', 'xinrenlei', 'byjy', 'czqcyy', 'clbabytiandi', 'fabeiniu', 'jzaibaby', 'fqyaya', 'nbmamibaby', 'yqmamalove', 'youyimy', 'bzyqyy', 'shgoldsun', 'xwmaidibaby', 'gtboygirl', 'cddiaodiao', 'npkekeya', 'fddamuzhi', 'whyuertang', 'xcbeierjiazu', 'lyguanjunbaby', 'mtyunzhiai', 'xybuyingfang', 'wwqinzileyuan', 'czaiyingjiayuan', 'yzbeibeiyy', 'czhjyy', 'hfaibaoer', 'xmaixiami', 'pcmamiai', 'ngdiandian', 'jnyft', 'jddiandian', 'zpttl', 'lpxbl', 'lxdodoisland', 'yxmyf', 'gdxtzgg', 'scbbyuan', 'aqaxqzy', 'shtaobaby', 'sysjza', 'ssjjw', 'jxzhn', 'sunshinebaby', 'swxyy', 'pzhappybud', 'fsaibama', 'nycnyy', 'lyxiaozeng', 'tzlzz', 'qyhappybaby', 'scayf', 'cfyrbb', 'pjbeiler', 'hfqjmy', 'dywlmm', 'lxayjbb', 'jnhengjunber', 'thmmbb', 'ssmiergang', 'houhaizi', 'gybaobeier', 'aqjbb', 'xhyyzj', 'alggb', 'tltfbb', 'yxnzly', 'hfyybs', 'yyplmm', 'yfxty', 'wzalbb', 'sshjbb', 'hxxxzj', 'ffzyyy', 'szxsbb', 'xshjsy', 'tszyyy', 'bjzyyy', 'yymml', 'qlxflk', 'hmaxbb', 'dchyyy', 'wsygbb', 'xzzamy', 'qsnzly', 'cslfbb', 'nzklbb', 'gyybly', 'ptbbboom', 'jnbym', 'hyjyhhz', 'ddjsts', 'hshjmy', 'szaayy', 'wabbbm', 'zxtrsy', 'ydmysj', 'wwzyyy', 'kpdcyy', 'yxayb', 'hzby', 'hdayy', 'xgymmy', 'axhk', 'dljbb', 'hmmy', 'ya0697', 'ya0782', 'ya0783', 'ya0799', 'ya0800', 'ya0809', 'ya0810', 'ya0897', 'ya0898', 'ya0899', 'smlsyl', 'xabbs', 'xgc', 'bdymc']
unnormal_promotion_org_list = ['muyingyuan', 'ygyj', 'loveheart', 'beibei', 'mamibaobei', 'yybb', 'jdb', 'mamabb', 'sunnybaby', 'subujyl', 'czqcyy', 'clbabytiandi', 'jzaibaby', 'fqyaya', 'nbmamibaby', 'yqmamalove', 'youyimy', 'bzyqyy', 'xwmaidibaby', 'cddiaodiao', 'npkekeya', 'fddamuzhi', 'xcbeierjiazu', 'lyguanjunbaby', 'xybuyingfang', 'nphoneybaby', 'czaiyingjiayuan', 'yzbeibeiyy', 'czhjyy', 'hfaibaoer', 'npfuwawa', 'xmaixiami', 'zpttl', 'lpxbl', 'hkhaohaizi', 'lxdodoisland', 'lzsimier', 'gdxtzgg', 'aqaxqzy', 'sysjza', 'ssjjw', 'jxzhn', 'swxyy', 'pzhappybud', 'lyxiaozeng', 'tzlzz', 'qyhappybaby', 'scayf', 'lxayjbb', 'thmmbb', 'wzhjbb', 'ssmiergang', 'houhaizi', 'aqjbb', 'xhyyzj', 'alggb', 'hfyybs', 'yfxty', 'wzalbb', 'ffzyyy', 'szxsbb', 'yymml', 'qlxflk', 'wsygbb', 'xzzamy', 'qsnzly', 'gyybly', 'ptbbboom', 'hyjyhhz', 'ddjsts', 'hshjmy', 'wabbbm', 'zxtrsy', 'kpdcyy', 'hzby', 'hdayy', 'axhk', 'alxsd', 'sybbx', 'hmmy', 'ya0697', 'ya0782', 'ya0783', 'ya0799', 'ya0800', 'ya0809', 'ya0810', 'ya0897', 'ya0898', 'ya0899']
unnormal_marketing_org_list = ['jinyaolan', 'muyingyuan', 'ygyj', 'loveheart', 'leyaya', 'aiying', 'jiajia', 'yyplan', 'yingyuan', 'beibei', 'babycare', 'mamibaobei', 'yybb', 'jdb', 'dd', 'mamabb', 'congcong', 'sunnybaby', 'yaerbaby', 'muyingfang', 'wlmami', 'aiyingfang', 'dtaiyingfang', 'loveangel', 'keai', 'harneybaby', 'lebao', 'heartlove', 'subujyl', 'byjy', 'ndabd', 'xzbym', 'ptbabyplan', 'czqcyy', 'clbabytiandi', 'hdguzi', 'jzaibaby', 'lsdsyy', 'fqyaya', 'nbmamibaby', 'yqmamalove', 'youyimy', 'bzyqyy', 'tzbaobaokang', 'shgoldsun', 'xwmaidibaby', 'gtboygirl', 'cddiaodiao', 'npkekeya', 'nbwljz', 'fddamuzhi', 'whyuertang', 'xcbeierjiazu', 'lyguanjunbaby', 'mtyunzhiai', 'xsbaobaier', 'xybuyingfang', 'nphoneybaby', 'wwqinzileyuan', 'czaiyingjiayuan', 'yzbeibeiyy', 'czhjyy', 'hfaibaoer', 'xmaixiami', 'pcmamiai', 'ngdiandian', 'jnyft', 'jddiandian', 'zpttl', 'lpxbl', 'hkhaohaizi', 'lxdodoisland', 'yxmyf', 'aqmmbb', 'gdxtzgg', 'scbbyuan', 'aqaxqzy', 'wplyf', 'shtaobaby', 'sysjza', 'ssjjw', 'cdqxy', 'sunshinebaby', 'swxyy', 'pzhappybud', 'fsaibama', 'nycnyy', 'lyxiaozeng', 'hzqzf', 'fgjbb', 'tzlzz', 'qyhappybaby', 'scayf', 'yhbbjh', 'cfyrbb', 'pjbeiler', 'hfqjmy', 'dywlmm', 'lxayjbb', 'jnhengjunber', 'thmmbb', 'ssmiergang', 'tchjbb', 'houhaizi', 'gybaobeier', 'aqjbb', 'xtytxf', 'xhyyzj', 'alggb', 'tltfbb', 'yxnzly', 'fjyyb', 'hfyybs', 'yyplmm', 'ezbbw', 'yfxty', 'wzalbb', 'sshjbb', 'hxxxzj', 'ffzyyy', 'wllyw', 'rjaxmm', 'ncbbwg', 'szxsbb', 'xshjsy', 'qabmhw', 'tszyyy', 'bjzyyy', 'yymml', 'qlxflk', 'psayw', 'hmaxbb', 'axyjq', 'dchyyy', 'hsxxbb', 'hdswyy', 'wsygbb', 'xzzamy', 'qsnzly', 'cslfbb', 'nzklbb', 'gyybly', 'ptbbboom', 'jnbym', 'hyjyhhz', 'ddjsts', 'hshjmy', 'szaayy', 'wabbbm', 'zxtrsy', 'ydmysj', 'kpdcyy', 'yxayb', 'hzby', 'hdayy', 'xgymmy', 'axhk', 'alxsd', 'sybbx', 'dljbb', 'zzayf', 'lnbeyt', 'cdkeyy', 'hmmy', 'ya0697', 'ya0782', 'ya0783', 'ya0799', 'ya0800', 'ya0809', 'ya0810', 'ya0897', 'ya0898', 'ya0899', 'smlsyl', 'jsayf', 'xabbs', 'xgc', 'lyccayf']

for  i in unnormal_marketing_org_list:
    if (i in unnormal_member_org_list) & (i in unnormal_prize_org_list) & (i in unnormal_promotion_org_list):
        print(i)


org_code_list = ['jinyaolan','aitiantian','muyingyuan','haoshijie','ygyj','lebaby','loveheart','jinbaby','leyaya','aiying','aier','jiajia','yyplan','yingyuan','beibei','growgarden','babycare','jodafengche','mamibaobei','yybb','jdb','dd','mamabb','congcong','chenbaby','wanpf','sunnybaby','yaerbaby','muyingfang','wlmami','aiyingfang','dtaiyingfang','loveangel','keai','harneybaby','lebao','heartlove','babycountry','subujyl','jialibaby','yujiababy','xinrenlei','byjy','bearhouse','hefeijyl','ndabd','lzyyb','xzbym','ptbabyplan','czqcyy','clbabytiandi','sxqzf','fabeiniu','hdguzi','xatonghuiyy','dychouchou','jzaibaby','lsdsyy','fqyaya','nbmamibaby','yqmamalove','smhybb','youyimy','pxkaixinbaby','bzyqyy','tzbaobaokang','shgoldsun','xwmaidibaby','gtboygirl','cddiaodiao','xcyangguangyy','npkekeya','nbwljz','jayunyingzhijia','smjiajiale','fddamuzhi','whyuertang','dgaiyibaby','xcbeierjiazu','lyguanjunbaby','mtyunzhiai','xsbaobaier','xybuyingfang','ljcongmingbaby','nphoneybaby','wwqinzileyuan','czaiyingjiayuan','yzbeibeiyy','czhjyy','xraixingyuan','hfaibaoer','npfuwawa','xmaixiami','pcmamiai','ngdiandian','jnyft','rcrealbaby','hsmmsj','jddiandian','zpttl','lpxbl','hkhaohaizi','lxdodoisland','yxmyf','lzsimier','aqmmbb','gdxtzgg','scbbyuan','aqaxqzy','wplyf','shtaobaby','sysjza','ssjjw','cdqxy','jxzhn','yjasd','sunshinebaby','swxyy','pzhappybud','fsaibama','nycnyy','jyjew','stjeg','lyxiaozeng','hzqzf','shxxyd','fgjbb','tzlzz','qyhappybaby','scayf','ldyzb','yhbbjh','cfyrbb','pjbeiler','hfqjmy','dywlmm','lxayjbb','jnhengjunber','thmmbb','wzhjbb','ssmiergang','tchjbb','houhaizi','gybaobeier','aqjbb','xtytxf','xhyyzj','alggb','tltfbb','lerobaby','yxnzly','bztsbb','fjyyb','hfyybs','yyplmm','gynwbb','ezbbw','yfxty','wzalbb','sshjbb','hxxxzj','ffzyyy','wllyw','rjaxmm','wzyza','ncbbwg','dyxinya','szxsbb','xshjsy','qabmhw','tszyyy','bjzyyy','yymml','qlxflk','psayw','fljz','gdfbb','zsxtd','hmaxbb','sldyzyy','axyjq','dchyyy','hsxxbb','hdswyy','wsygbb','xzzamy','qsnzly','cslfbb','garhmy','frjeyy','nzklbb','gyybly','ptbbboom','xpxxbn','jnbym','hyjyhhz','tnygbb','ddjsts','hshjmy','szaayy','wabbbm','zxtrsy','swjhsm','ydmysj','wwzyyy','kpdcyy','yxayb','hzby','hdayy','xgymmy','axhk','ycxjl','szgz','hzcc','alxsd','dtbyx','nswab','sybbx','dljbb','zzayf','lmqs','lnbeyt','xtaed','cdkeyy','jaccyy','xambt','hmmy','ya0697','ya0782','ya0783','ya0799','ya0800','ya0809','ya0810','ya0897','ya0898','ya0899','smlsyl','wlbbq','jsayf','xabbs','btymb','dxzyyy','xgc','lyccayf','bdymc']

unnormal_org_list = ['muyingyuan','mamibaobei','sunnybaby','yqmamalove','bzyqyy','xwmaidibaby','czhjyy','lxdodoisland','gdxtzgg','sysjza','qyhappybaby','scayf','aqjbb','hfyybs','yfxty','yymml','ptbbboom','ddjsts','hshjmy','kpdcyy','hmmy','ya0697','ya0782','ya0783','ya0799','ya0800','ya0809','ya0810','ya0897','ya0898','ya0899']

print(set(org_code_list)-set(unnormal_org_list))